name: ci

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "lib/**"
      - "*.gemspec"
      - "spec/**"
      - "Rakefile"
      - "Gemfile"
      - ".rubocop.yml"
  pull_request:
    branches:
      - master
  create:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
        db:
          - sqlite3
          - mysql
          - postgresql
    env:
      DB: ${{matrix.db}}
      HANAMI_DATABASE_USERNAME: runner
      HANAMI_DATABASE_PASSWORD: runner
      HANAMI_DATABASE_HOST: 127.0.0.1
      HANAMI_DATABASE_NAME: hanami_model
    steps:
      - uses: actions/checkout@v1
      - name: Install package dependencies
        run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{matrix.ruby}}
      - name: Set up PostgreSQL using VM server
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "CREATE USER ${{ env.HANAMI_DATABASE_USERNAME }} WITH SUPERUSER PASSWORD '${{ env.HANAMI_DATABASE_PASSWORD }}'"
          sudo createdb ${{ env.HANAMI_DATABASE_NAME}}
        env:
          HANAMI_DATABASE_NAME: hanami_model
        if: ${{ matrix.db == 'postgresql' }}
      - name: Set up MySQL using VM server
        run: |
          sudo systemctl start mysql.service
          mysql -u root -proot -e "create database ${{ env.HANAMI_DATABASE_NAME }}";
        if: ${{ matrix.db == 'mysql' }}
      - run: rm -rf coverage
      - run: bundle exec rubocop .
      - run: bundle exec rspec spec/**/*_spec.rb
      - run: bundle exec rake codecov:upload
